### ISSUE TITLE
running as default params is not working 

### ISSUE THREAD

**Issue by verystrongjoe** [fshamshirdar/pytorch-rdpg#1]
D:\temp\Python35\python.exe C:/Git/pytorch-rdpg/main.py
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
D:\temp\Python35\lib\site-packages\gym\__init__.py:15: UserWarning: gym.undo_logger_setup is deprecated. gym no longer modifies the global logging configuration
  warnings.warn("gym.undo_logger_setup is deprecated. gym no longer modifies the global logging configuration")
Traceback (most recent call last):
  File "C:/Git/pytorch-rdpg/main.py", line 58, in <module>
    rdpg.train(args.train_iter, args.checkpoint, args.debug)
  File "C:\Git\pytorch-rdpg\rdpg.py", line 88, in train
    self.update_policy()
  File "C:\Git\pytorch-rdpg\rdpg.py", line 117, in update_policy
    experiences = self.memory.sample(self.batch_size)
  File "C:\Git\pytorch-rdpg\memory.py", line 284, in sample
    batch = [self.sample_trajectory(maxlen=maxlen) for _ in range(batch_size)]
  File "C:\Git\pytorch-rdpg\memory.py", line 284, in <listcomp>
    batch = [self.sample_trajectory(maxlen=maxlen) for _ in range(batch_size)]
  File "C:\Git\pytorch-rdpg\memory.py", line 295, in sample_trajectory
    if maxlen > 0 and T > maxlen + 1:
TypeError: unorderable types: NoneType() > int()
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x0000016711439C18>>
Traceback (most recent call last):
  File "D:\temp\Python35\lib\site-packages\gym\envs\classic_control\rendering.py", line 143, in __del__
  File "D:\temp\Python35\lib\site-packages\gym\envs\classic_control\rendering.py", line 62, in close
  File "D:\temp\Python35\lib\site-packages\pyglet\window\win32\__init__.py", line 305, in close
  File "D:\temp\Python35\lib\site-packages\pyglet\window\__init__.py", line 770, in close
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable

Process finished with exit code 1

**Comment by fshamshirdar** [comment]
I've added the requirements file. Tested by python2.7, but you could give it a try on python3.5.
You're welcome to create a pull requests supporting other versions
